// SPDX-FileCopyrightText: GARDENA GmbH
//
// SPDX-License-Identifier: MIT

//! Unsafe Rust bindings to liblsdl-serializer

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

// Initially this was generated by bindgen but for some reason it can't find
// `stddef.h` in yocto so I just copied the result in here.
extern "C" {
    pub fn compressXML(
        port: ::std::os::raw::c_ushort,
        xmlBuf: *mut ::std::os::raw::c_uchar,
        xmlBufLen: ::std::os::raw::c_ulong,
        exiBuf: *mut ::std::os::raw::c_uchar,
        exiBufLen: ::std::os::raw::c_ulong,
        bitOffset: ::std::os::raw::c_ulong,
    ) -> ::std::os::raw::c_ulong;

    pub fn decompressEXI(
        port: ::std::os::raw::c_ushort,
        exiBuf: *mut ::std::os::raw::c_uchar,
        exiBufLen: ::std::os::raw::c_ulong,
        xmlBuf: *mut ::std::os::raw::c_uchar,
        xmlBufLen: ::std::os::raw::c_ulong,
        bitOffset: ::std::os::raw::c_ulong,
    ) -> ::std::os::raw::c_ulong;

    pub fn lsdlconv_getVersion() -> *const ::std::os::raw::c_char;
}
